
# Generated by CodiumAI

from pythonSpecific.mixs import Opt

import pytest

class TestOpt:

    #  Initialize Opt with default values and check addition
    def test_default_values_addition(self):
        o = Opt()
        assert o.add() == 30

    #  Initialize Opt with zero values and check addition
    def test_zero_values_addition(self):
        o = Opt(a=0, b=0)
        assert o.add() == 0

    #  Initialize Opt with default values and check subtraction
    def test_initialize_with_default_values_and_check_subtraction(self):
        opt = Opt()
        assert opt.a == 10
        assert opt.b == 20
        assert opt.sub() == -10

    #  Initialize Opt with custom values and check addition
    def test_initialize_with_custom_values_and_check_addition(self):
        o = Opt(a=15, b=25)
        result = o.add()
        assert result == 40

    #  Initialize Opt with custom values and check subtraction
    def test_initialize_with_custom_values_and_check_subtraction(self):
        opt = Opt(a=15, b=5)
        result = opt.sub()
        assert result == 10

    #  Ensure Opt can access methods from AddMixin and SubMixin
    def test_opt_access_methods(self):
        opt = Opt()
        assert opt.add() == 30
        assert opt.sub() == -10
